### ISSUE TITLE
Add a screen with map and GPS

### ISSUE THREAD

**Issue by krook** [Pyrrha-Platform/Pyrrha-Dashboard#128]
In the next milestone, we are adding GPS capabilities to the mobile app, so we need to update the dashboard to reflect the location. 

There's potentially a reusable Mapbox component in the [OpenEEW dashboard](https://dashboard.openeew.com/events).

- [x] Add Mapbox token and instructions
- [x] Add the new page with the Mapbox
- [x] Update navigation to point to it
- [ ] Add long/lat handling with error handling if not present
- [ ] Ensure the database and managers provide long/lat

**Comment by krook** [comment]
Will use the OpenEEW dashboard code as the starting point.

**Comment by upkarlidder** [comment]
@mrodrise to add sample location JSON coming from the IoT service.

```

```
