### ISSUE TITLE
Add Docker Compose playbook for the dashboard

### ISSUE THREAD

**Issue by upkarlidder** [Pyrrha-Platform/Pyrrha-Dashboard#93]
The dashboard has three components that work in three docker containers
- Flask API
- React.js front end
- Authentication API (Node.js)

Create a docker compose file that brings up all the components together.

@krook FYI

**Comment by krook** [comment]
So this would be the local development use case right @upkarlidder?

**Comment by upkarlidder** [comment]
> So this would be the local development use case right @upkarlidder?

Yes, that is correct. As a developer, I should be able to get all components running on my local environment with `docker compose up`.

**Comment by upkarlidder** [comment]
This issue is completed. Created a new [instructions file](https://github.com/Pyrrha-Platform/Pyrrha-Deployment-Configurations/blob/main/DOCKER_COMPOSE.md) for docker-compose in the Configurations repo.
